### ISSUE TITLE
[BCK-64] Stocks, Futures, Options implementacija za firme

### ISSUE THREAD

**Issue by strahinja-ljubicicRN71-20** [RAF-SI-2023/Banka-3-Backend#164]

**Comment by ognjen10021rn** [comment]
**Vise detalja:**

**Option je isto sto i stock (OPTION = STOCK)**
Option je stock na akciji nekoj ali u sustini je isto kao i kupovina stocka.

Kada se uloguje firma, treba podrzati da moze firma da kupuje stocks, futures, i options. Kada firma kupi neki stock, future ili options treba da se kreiraju MyStock, MyFuture (za Option isto ide MyStock) za tu kompaniju (userId je 0) i setuje se companyId. Future kada se kupuje sa berze moze da se uzme samo 1, nema amount kao kod stockova.

**Treba kao dodatak i da se uradi OTC za firme:**

Implementacija trgovine stockova, futura, i optionsa izmedju firmi. 
Kada se uloguje firma ona moze da postavi da su stockovi/optionsi i futuri privatni ili public. Future doduse ima samo jedan.
Kada se stavi da je public neka druga firma moze da kupi akciju gde salje amount i price za tu akciju a kod futura samo price.
Ako neka firma odluci da kupi akciju kreira se Contract, (StockContract) koji je isti za usera samo sto se ne setuje userSellerId i buyer nego samo za firmu. A kod futura se pravi FutureContract. 

Treba napraviti getAll za supervizore koji ce videti sve moguce contracte za future i stockove.
GetAll za firmu da moze da vidi zahteve koje je ona poslala, analogno prodavcu da stigne dto gde firma zeli da kupi njihov stock ili future.... Prikazivace se status koji je PROCESSING ako je bar jedan od sertifikata PROCESSING, DECLINED ako je bar jedan DECLINED i ACCEPTED samo ako su oba ACCEPTED. Treba da bude i ticker, amount i price sto se tice stocka, a za future contractName i price.

Kada se podnese zahtev za kupovinu od neke firme. Seller tog stocka mora da prihvati ili odbije. Ako prihvati stavimo SellerCertificate na ACCEPTED. Tek kada firma prihvati odn seller onda se to salje supervizoru u njegovu listu. Isto mora i Supervizor na svom view-u da odobri i onda se stavlja BankCertificate na ACCEPTED. Firma ako odbija ima opciju da doda neki komentar isto tako i supervizor moze da stavi komentar ako odbije. Ako firma odmah stavi DECLINED ne salje se supervizoru i stavlja se neki komentar ili ako supervizor odbije i on moze da stavi neki komentar.

StockContract
![image](https://github.com/RAF-SI-2023/Banka-3-Backend/assets/92787793/0ee785b7-b89e-4344-b166-94f1111ca7de)

FutureContract
![image](https://github.com/RAF-SI-2023/Banka-3-Backend/assets/92787793/2d8f5e36-f216-42cf-af80-0808b8542250)
